openapi: 3.1.0
info: 
  title: API сервер для проекта  «Семь городов».
  description: |-
    *Список ресурсов и маршрутов сервера «Семь городов».
  license:
    name: MIT
    url: thhps://opensource.org/licenses/MIT
  version: 1.0.0