export type MockData = {
    titles: string[],
    descriptions: string[],
    cities: string[],
    previewImages: string[],
    images: string[],
    houseType: string[],
    listAmenities: string[],
    names: string[],
    emails: string[],
    avatars: string[],
    passwords: string[],
    userTypes: string[],
    locations: string[],
};
